#!/bin/bash

dir="$(cd "$(dirname "$0")" && pwd)"
echo "$dir"
cd "$dir"

ln -s "$dir/.hammerspoon" "$HOME/.hammerspoon"

mkdir "$HOME/Library/Application Support/nushell"
ln -s "$dir/nushell/config.nu" "$HOME/Library/Application Support/nushell/config.nu"


mkdir "$HOME/.config"
ln -s "$dir/nvim" "$HOME/.config/nvim"
ln -s "$dir/bat" "$HOME/.config/bat"
ln -s "$dir/btop" "$HOME/.config/btop"
ln -s "$dir/zed" "$HOME/.config/zed"
ln -s "$dir/ghostty" "$HOME/.config/ghostty"
mkdir "$HOME/.gnupg"
ln -s "$dir/gpg/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"
ln -s "$dir/gpg/gpg.conf" "$HOME/.gnupg/gpg.conf"

mkdir "$HOME/.config/git"
ln -s "$dir/git/.config/git/ignore" "$HOME/.config/git/ignore"
ln -s "$dir/git/.config/git/themes.gitconfig" "$HOME/.config/git/themes.gitconfig"

ln -s "$dir/git/.gitconfig" "$HOME/.gitconfig"
ln -s "$dir/homebrew/.Brewfile" "$HOME/.Brewfile"
ln -s "$dir/zsh/.zpath" "$HOME/.zpath"
ln -s "$dir/zsh/.zprofile" "$HOME/.zprofile"
ln -s "$dir/zsh/.zshenv" "$HOME/.zshenv"
ln -s "$dir/zsh/.zshrc" "$HOME/.zshrc"
ln -s "$dir/ssh/config" "$HOME/.ssh/config"


ln -s "$dir/starship/starship.toml" "$HOME/.config/starship.toml"
